=== FlyBirdGameStudio/Cubecraft/resources/resource/ui/faml.dtd
<?xml version="1.0" encoding="" ?>


        <!ATTLIST faml ext #PCDATA #REQUIRED>


        <!ATTLIST button, id #PCDATA #REQUIRED>
        <!ATTLIST label, id #PCDATA #REQUIRED>

        <!ELEMENT layout (#PCDATA>
        <!ELEMENT text (#PCDATA)>

        <!ATTLIST text type ("lang"|"raw"|"random") #REQUIRED)>
        <!ATTLIST text color #PCDATA #REQUIRED>
        <!ATTLIST text align ("left"|"middle"|"right") #REQUIRED>

        <!ATTLIST button,label,splash,image id #PCDATA #REQUIRED>

    <!ELEMENT faml (meta,elements)>
        <!ELEMENT meta (id,type,parent?)>
            <!ELEMENT id (#PCDATA)>
            <!ELEMENT type (#PCDATA)>
            <!ELEMENT parent (#PCDATA)>
        <!ELEMENT elements (button*,label*,splash*,image*)>
            <!ELEMENT button (layout,text)>
            <!ELEMENT label (layout,text)>
            <!ELEMENT splash (layout,text)>
            <!ELEMENT image (layout)>
                <!ATTLIST image img #PCDATA #REQUIRED>
                <!ATTLIST image h-clip ("left"|"middle"|"right") #REQUIRED>
                <!ATTLIST image v-clip ("top"|"middle"|"bottom") #REQUIRED>

=== FlyBirdGameStudio/Cubecraft/resources/resource/ui/video_setting_screen.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE faml SYSTEM "/faml.dtd">
<faml>
    <meta>
        <id>cubecraft:video_setting_screen</id>
        <type>super</type>
        <parent>super</parent>
    </meta>
    <elements>
        <label>
            <layout>{
                "type": "origin", "layout": [0,-10,300,30],
                "meta": "middle_middle", "layer": 0,"border":[0,0,4,4]
                }
            </layout>
            <text type="lang" color="ffffff" align="middle">option.video.title</text>
        </label>
    </elements>
</faml>
